"""
Test pipeline for the DMHOA email funnel + case analysis.

Lets the dashboard create fake test cases, advance them through the funnel
stages, manually trigger the nudge runner, and generate the full Claude
analysis ("plan") on demand. Every test row is tagged so cleanup is safe
and deterministic.

Tagging conventions (used by cleanup):
  - Test case tokens always start with "case_test_"
  - Test cases also have payload.test_run = true

All endpoints live under /api/dashboard/test-funnel.
"""

import os
import json
import logging
import secrets
import threading
from datetime import datetime, timezone
from typing import Dict, List, Optional

import requests
from flask import Blueprint, request, jsonify

from utils.funnel import log_funnel_stage
from utils import email_templates
from utils.email import send_email

logger = logging.getLogger(__name__)

test_funnel_bp = Blueprint('test_funnel', __name__)

SUPABASE_URL = os.environ.get('SUPABASE_URL')
SUPABASE_SERVICE_ROLE_KEY = os.environ.get('SUPABASE_SERVICE_ROLE_KEY')
TIMEOUT = (5, 60)

TEST_TOKEN_PREFIX = 'case_test_'


def supabase_headers() -> Dict[str, str]:
    return {
        'apikey': SUPABASE_SERVICE_ROLE_KEY,
        'Authorization': f'Bearer {SUPABASE_SERVICE_ROLE_KEY}',
        'Content-Type': 'application/json',
    }


def _is_test_token(token: str) -> bool:
    return bool(token) and token.startswith(TEST_TOKEN_PREFIX)


def _generate_test_token() -> str:
    """Build a unique tagged token for a test run."""
    ts = int(datetime.now(timezone.utc).timestamp())
    suffix = secrets.token_hex(4)
    return f'{TEST_TOKEN_PREFIX}{ts}_{suffix}'


def _delete_supabase_rows(table: str, params: dict) -> int:
    """Delete rows from a Supabase table by query params. Returns row count or -1 on error."""
    if not SUPABASE_URL or not SUPABASE_SERVICE_ROLE_KEY:
        return -1
    try:
        headers = {**supabase_headers(), 'Prefer': 'return=representation'}
        resp = requests.delete(
            f'{SUPABASE_URL}/rest/v1/{table}',
            headers=headers,
            params=params,
            timeout=TIMEOUT,
        )
        if resp.ok:
            try:
                return len(resp.json() or [])
            except Exception:
                return 0
        logger.warning(f'Delete {table} failed: HTTP {resp.status_code} - {resp.text[:200]}')
        return -1
    except Exception as e:
        logger.error(f'Delete {table} exception: {e}')
        return -1


# ----------------------------------------------------------------------------
# CREATE A TEST CASE
# ----------------------------------------------------------------------------

@test_funnel_bp.route('/api/dashboard/test-funnel/create', methods=['POST', 'OPTIONS'])
def create_test_case():
    """Create a tagged test case and immediately advance funnel to quick_preview_complete.

    Body: { "email": "test@example.com" }
    """
    if request.method == 'OPTIONS':
        return jsonify({'message': 'OK'})

    if not SUPABASE_URL or not SUPABASE_SERVICE_ROLE_KEY:
        return jsonify({'error': 'Supabase not configured'}), 500

    body = request.get_json(silent=True) or {}
    email = (body.get('email') or '').strip()
    if not email or '@' not in email:
        return jsonify({'error': 'Valid email required'}), 400

    token = _generate_test_token()

    # Build a minimal but valid payload mirroring what /api/save-case stores.
    payload = {
        'email': email,
        'test_run': True,
        'noticeType': 'TEST - Violation Notice',
        'issueText': 'This is a synthetic test case generated by the dashboard test pipeline.',
        'amount': 250,
        'state': 'GA',
        'fullCaseFormLink': f'https://disputemyhoa.com/case-preview/{token}',
        'submittedAt': datetime.now(timezone.utc).isoformat(),
    }

    case_data = {
        'token': token,
        'email': email,
        'payload': payload,
        'status': 'quick_preview',
    }

    try:
        resp = requests.post(
            f'{SUPABASE_URL}/rest/v1/dmhoa_cases',
            headers={**supabase_headers(), 'Prefer': 'return=representation'},
            json=case_data,
            timeout=TIMEOUT,
        )
        if not resp.ok:
            return jsonify({
                'error': 'Failed to insert test case',
                'detail': resp.text[:500],
            }), 500
        rows = resp.json() or []
        case_row = rows[0] if rows else case_data
    except Exception as e:
        logger.error(f'Test case create failed: {e}')
        return jsonify({'error': str(e)}), 500

    # Fire the funnel stage hook (this also sends the immediate quick_preview email)
    funnel_advanced = log_funnel_stage(email, 'quick_preview_complete', payload['fullCaseFormLink'])

    return jsonify({
        'ok': True,
        'token': token,
        'email': email,
        'case': {
            'id': case_row.get('id'),
            'token': token,
            'status': case_row.get('status', 'quick_preview'),
        },
        'funnel_advanced': funnel_advanced,
        'message': 'Test case created. Quick preview email sent.',
    })


# ----------------------------------------------------------------------------
# ADVANCE A TEST CASE TO THE NEXT STAGE
# ----------------------------------------------------------------------------

@test_funnel_bp.route('/api/dashboard/test-funnel/<token>/advance', methods=['POST', 'OPTIONS'])
def advance_test_case(token):
    """Advance a test case to the named stage.

    Body: { "stage": "full_preview_viewed" | "purchased" }
    Only test-tagged tokens are accepted.
    """
    if request.method == 'OPTIONS':
        return jsonify({'message': 'OK'})

    if not _is_test_token(token):
        return jsonify({'error': 'Refusing to advance a non-test token'}), 400

    body = request.get_json(silent=True) or {}
    target_stage = (body.get('stage') or '').strip()
    if target_stage not in ('full_preview_viewed', 'purchased'):
        return jsonify({'error': 'stage must be full_preview_viewed or purchased'}), 400

    # Look up the case
    try:
        resp = requests.get(
            f'{SUPABASE_URL}/rest/v1/dmhoa_cases',
            headers=supabase_headers(),
            params={'token': f'eq.{token}', 'select': 'id,token,email,payload,status'},
            timeout=TIMEOUT,
        )
        if not resp.ok:
            return jsonify({'error': 'Failed to fetch test case', 'detail': resp.text[:300]}), 500
        rows = resp.json() or []
        if not rows:
            return jsonify({'error': 'Test case not found'}), 404
        case = rows[0]
    except Exception as e:
        return jsonify({'error': str(e)}), 500

    case_payload = case.get('payload') or {}
    if isinstance(case_payload, str):
        try:
            case_payload = json.loads(case_payload)
        except Exception:
            case_payload = {}

    email = case.get('email') or case_payload.get('email')
    if not email:
        return jsonify({'error': 'Test case has no email'}), 400

    # Build the link passed into the email template
    if target_stage == 'full_preview_viewed':
        link = f'https://disputemyhoa.com/case-preview/{token}'
    else:  # purchased
        link = f'https://disputemyhoa.com/case/{token}'
        # Mark the case as paid so the rest of the dashboard sees it correctly
        try:
            requests.patch(
                f'{SUPABASE_URL}/rest/v1/dmhoa_cases',
                headers=supabase_headers(),
                params={'token': f'eq.{token}'},
                json={'status': 'paid'},
                timeout=TIMEOUT,
            )
        except Exception as e:
            logger.warning(f'Failed to mark test case paid: {e}')

    funnel_advanced = log_funnel_stage(email, target_stage, link)

    return jsonify({
        'ok': True,
        'token': token,
        'email': email,
        'stage': target_stage,
        'funnel_advanced': funnel_advanced,
        'message': f'Advanced to {target_stage}' if funnel_advanced else 'Already at or past this stage',
    })


# ----------------------------------------------------------------------------
# GENERATE FULL PLAN (CASE ANALYSIS) FOR A TEST CASE
# ----------------------------------------------------------------------------

@test_funnel_bp.route('/api/dashboard/test-funnel/<token>/generate-plan', methods=['POST', 'OPTIONS'])
def generate_test_plan(token):
    """Run the full Claude case analysis for a test case in a background thread.

    The dashboard polls /case-analysis-status to see when it completes.
    """
    if request.method == 'OPTIONS':
        return jsonify({'message': 'OK'})

    if not _is_test_token(token):
        return jsonify({'error': 'Refusing to generate plan for a non-test token'}), 400

    # Lazy import to avoid circular dependency at module load
    try:
        from app import run_case_analysis
    except Exception as e:
        return jsonify({'error': f'Could not import run_case_analysis: {e}'}), 500

    def _run():
        try:
            logger.info(f'Test pipeline: starting plan generation for {token}')
            result = run_case_analysis(token)
            logger.info(f'Test pipeline: plan generation complete for {token}: status={result.get("status") if isinstance(result, dict) else "unknown"}')
        except Exception as e:
            logger.error(f'Test pipeline: plan generation failed for {token}: {e}')

    try:
        t = threading.Thread(target=_run, daemon=True)
        t.start()
    except Exception as e:
        return jsonify({'ok': False, 'error': str(e)}), 500

    return jsonify({
        'ok': True,
        'token': token,
        'message': 'Plan generation started in background. Check status in 30-60 seconds.',
    })


@test_funnel_bp.route('/api/dashboard/test-funnel/<token>/plan-status', methods=['GET', 'OPTIONS'])
def get_plan_status(token):
    """Return the current case analysis status for a test case."""
    if request.method == 'OPTIONS':
        return jsonify({'message': 'OK'})

    if not _is_test_token(token):
        return jsonify({'error': 'Refusing non-test token'}), 400

    try:
        # Look up the case to get id
        resp = requests.get(
            f'{SUPABASE_URL}/rest/v1/dmhoa_cases',
            headers=supabase_headers(),
            params={'token': f'eq.{token}', 'select': 'id'},
            timeout=TIMEOUT,
        )
        if not resp.ok or not resp.json():
            return jsonify({'error': 'Test case not found'}), 404
        case_id = resp.json()[0].get('id')

        # Check dmhoa_case_outputs for the analysis result
        out_resp = requests.get(
            f'{SUPABASE_URL}/rest/v1/dmhoa_case_outputs',
            headers=supabase_headers(),
            params={'case_id': f'eq.{case_id}', 'select': 'id,status,model,created_at', 'order': 'created_at.desc', 'limit': '1'},
            timeout=TIMEOUT,
        )
        if out_resp.ok:
            outs = out_resp.json() or []
            if outs:
                return jsonify({'has_plan': True, 'output': outs[0]})

        return jsonify({'has_plan': False})
    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ----------------------------------------------------------------------------
# MANUAL NUDGE RUN
# ----------------------------------------------------------------------------

@test_funnel_bp.route('/api/dashboard/test-funnel/run-nudges', methods=['POST', 'OPTIONS'])
def trigger_nudges_now():
    """Run the email nudge job immediately. Same logic as the 30-min scheduler."""
    if request.method == 'OPTIONS':
        return jsonify({'message': 'OK'})

    try:
        from jobs.email_nudges import _run_nudge_1, _run_nudge_2, _run_nudge_3
        n1 = _run_nudge_1()
        n2 = _run_nudge_2()
        n3 = _run_nudge_3()
        return jsonify({
            'ok': True,
            'nudge_1_sent': n1,
            'nudge_2_sent': n2,
            'nudge_3_sent': n3,
        })
    except Exception as e:
        logger.error(f'trigger_nudges_now failed: {e}')
        return jsonify({'ok': False, 'error': str(e)}), 500


# ----------------------------------------------------------------------------
# EMAIL TEMPLATE PREVIEW + STANDALONE TEST SEND
# Lets you inspect or send a single email of any template without touching
# the funnel state. Useful for tweaking copy and verifying deliverability.
# ----------------------------------------------------------------------------

EMAIL_TEMPLATES = {
    'quick_preview_confirmation': email_templates.quick_preview_confirmation,
    'nudge_1': email_templates.nudge_1,
    'nudge_2': email_templates.nudge_2,
    'nudge_3': email_templates.nudge_3,
    'purchase_confirmation': email_templates.purchase_confirmation,
}


@test_funnel_bp.route('/api/dashboard/test-funnel/email-preview/<template_name>', methods=['GET', 'OPTIONS'])
def preview_email_template(template_name):
    """Render any email template and return subject + body without sending.

    Optional query param: link=<url> to substitute into the template.
    """
    if request.method == 'OPTIONS':
        return jsonify({'message': 'OK'})

    if template_name not in EMAIL_TEMPLATES:
        return jsonify({
            'error': f'Unknown template: {template_name}',
            'available': sorted(EMAIL_TEMPLATES.keys()),
        }), 400

    link = request.args.get('link', 'https://disputemyhoa.com/case-preview/example')
    try:
        subject, body = EMAIL_TEMPLATES[template_name](link)
        return jsonify({
            'template': template_name,
            'subject': subject,
            'body': body,
            'link_used': link,
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@test_funnel_bp.route('/api/dashboard/test-funnel/send-test-email', methods=['POST', 'OPTIONS'])
def send_test_email():
    """Send a one-off email of any template to a specific address.

    Body: { "template": "nudge_1", "to": "you@example.com", "link": "..." (optional) }
    Does not touch the email_funnel table or any case data.
    """
    if request.method == 'OPTIONS':
        return jsonify({'message': 'OK'})

    body = request.get_json(silent=True) or {}
    template_name = (body.get('template') or '').strip()
    to_address = (body.get('to') or '').strip()
    link = (body.get('link') or 'https://disputemyhoa.com/case-preview/example').strip()

    if template_name not in EMAIL_TEMPLATES:
        return jsonify({
            'error': f'Unknown template: {template_name}',
            'available': sorted(EMAIL_TEMPLATES.keys()),
        }), 400

    if not to_address or '@' not in to_address:
        return jsonify({'error': 'Valid "to" email address required'}), 400

    try:
        subject, body_text = EMAIL_TEMPLATES[template_name](link)
        sent = send_email(to_address, subject, body_text)
        if sent:
            return jsonify({
                'ok': True,
                'message': f'Sent {template_name} to {to_address}',
                'subject': subject,
            })
        else:
            return jsonify({
                'ok': False,
                'error': 'Resend send returned non-success. Check Heroku logs and verify mail.disputemyhoa.com is configured in Resend.',
            }), 500
    except Exception as e:
        logger.error(f'send_test_email failed: {e}')
        return jsonify({'ok': False, 'error': str(e)}), 500


# ----------------------------------------------------------------------------
# LIST TEST CASES
# ----------------------------------------------------------------------------

@test_funnel_bp.route('/api/dashboard/test-funnel', methods=['GET', 'OPTIONS'])
def list_test_cases():
    """Return all tagged test cases with their funnel state."""
    if request.method == 'OPTIONS':
        return jsonify({'message': 'OK'})

    try:
        # Find all dmhoa_cases with test prefix
        resp = requests.get(
            f'{SUPABASE_URL}/rest/v1/dmhoa_cases',
            headers=supabase_headers(),
            params={
                'token': f'like.{TEST_TOKEN_PREFIX}*',
                'select': 'id,token,email,payload,status,created_at',
                'order': 'created_at.desc',
                'limit': '100',
            },
            timeout=TIMEOUT,
        )
        if not resp.ok:
            return jsonify({'error': 'Failed to list test cases', 'detail': resp.text[:300]}), 500
        cases = resp.json() or []

        # For each case, look up funnel state and analysis status
        results = []
        for case in cases:
            case_payload = case.get('payload') or {}
            if isinstance(case_payload, str):
                try:
                    case_payload = json.loads(case_payload)
                except Exception:
                    case_payload = {}
            email = case.get('email') or case_payload.get('email')

            funnel_row = None
            if email:
                try:
                    f_resp = requests.get(
                        f'{SUPABASE_URL}/rest/v1/email_funnel',
                        headers=supabase_headers(),
                        params={'email': f'eq.{email}', 'select': '*', 'limit': '1'},
                        timeout=TIMEOUT,
                    )
                    if f_resp.ok:
                        rows = f_resp.json() or []
                        if rows:
                            funnel_row = rows[0]
                except Exception:
                    pass

            has_plan = False
            try:
                out_resp = requests.get(
                    f'{SUPABASE_URL}/rest/v1/dmhoa_case_outputs',
                    headers=supabase_headers(),
                    params={'case_id': f'eq.{case["id"]}', 'select': 'id', 'limit': '1'},
                    timeout=TIMEOUT,
                )
                if out_resp.ok and out_resp.json():
                    has_plan = True
            except Exception:
                pass

            results.append({
                'id': case.get('id'),
                'token': case.get('token'),
                'email': email,
                'status': case.get('status'),
                'created_at': case.get('created_at'),
                'has_plan': has_plan,
                'funnel': funnel_row,
            })

        return jsonify({'cases': results})
    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ----------------------------------------------------------------------------
# DELETE A SINGLE TEST CASE (cascade across all related tables)
# ----------------------------------------------------------------------------

def _delete_test_case_artifacts(token: str, email: Optional[str], case_id: Optional[str]) -> Dict[str, int]:
    """Delete every Supabase row tied to a single test case."""
    deleted = {}
    if case_id:
        deleted['dmhoa_case_outputs'] = _delete_supabase_rows('dmhoa_case_outputs', {'case_id': f'eq.{case_id}'})
        deleted['dmhoa_case_previews'] = _delete_supabase_rows('dmhoa_case_previews', {'case_id': f'eq.{case_id}'})
        deleted['dmhoa_documents'] = _delete_supabase_rows('dmhoa_documents', {'case_id': f'eq.{case_id}'})
    deleted['dmhoa_messages'] = _delete_supabase_rows('dmhoa_messages', {'token': f'eq.{token}'})
    deleted['dmhoa_events'] = _delete_supabase_rows('dmhoa_events', {'token': f'eq.{token}'})
    deleted['dmhoa_cases'] = _delete_supabase_rows('dmhoa_cases', {'token': f'eq.{token}'})
    if email:
        deleted['email_funnel'] = _delete_supabase_rows('email_funnel', {'email': f'eq.{email}'})
    return deleted


@test_funnel_bp.route('/api/dashboard/test-funnel/<token>', methods=['DELETE', 'OPTIONS'])
def delete_test_case(token):
    """Delete a single test case and every Supabase row tied to it."""
    if request.method == 'OPTIONS':
        return jsonify({'message': 'OK'})

    if not _is_test_token(token):
        return jsonify({'error': 'Refusing to delete a non-test token'}), 400

    # Look up first to get id and email
    try:
        resp = requests.get(
            f'{SUPABASE_URL}/rest/v1/dmhoa_cases',
            headers=supabase_headers(),
            params={'token': f'eq.{token}', 'select': 'id,email,payload'},
            timeout=TIMEOUT,
        )
        rows = resp.json() if resp.ok else []
        case = rows[0] if rows else None
    except Exception as e:
        return jsonify({'error': str(e)}), 500

    case_id = None
    email = None
    if case:
        case_id = case.get('id')
        email = case.get('email')
        if not email:
            cp = case.get('payload') or {}
            if isinstance(cp, str):
                try:
                    cp = json.loads(cp)
                except Exception:
                    cp = {}
            email = cp.get('email')

    deleted = _delete_test_case_artifacts(token, email, case_id)
    return jsonify({'ok': True, 'token': token, 'deleted': deleted})


# ----------------------------------------------------------------------------
# DELETE ALL TEST CASES (bulk cleanup)
# ----------------------------------------------------------------------------

@test_funnel_bp.route('/api/dashboard/test-funnel', methods=['DELETE', 'OPTIONS'])
def delete_all_test_cases():
    """Delete every test-tagged case and every related Supabase row."""
    if request.method == 'OPTIONS':
        return jsonify({'message': 'OK'})

    try:
        resp = requests.get(
            f'{SUPABASE_URL}/rest/v1/dmhoa_cases',
            headers=supabase_headers(),
            params={'token': f'like.{TEST_TOKEN_PREFIX}*', 'select': 'id,token,email,payload', 'limit': '500'},
            timeout=TIMEOUT,
        )
        cases = resp.json() if resp.ok else []
    except Exception as e:
        return jsonify({'error': str(e)}), 500

    summary = {'cases_deleted': 0, 'tables': {}}
    for case in cases:
        token = case.get('token')
        case_id = case.get('id')
        email = case.get('email')
        if not email:
            cp = case.get('payload') or {}
            if isinstance(cp, str):
                try:
                    cp = json.loads(cp)
                except Exception:
                    cp = {}
            email = cp.get('email')

        deleted = _delete_test_case_artifacts(token, email, case_id)
        for table, count in deleted.items():
            summary['tables'][table] = summary['tables'].get(table, 0) + max(count, 0)
        summary['cases_deleted'] += 1

    return jsonify({'ok': True, **summary})
